baseURL: "https://blog.quarticcat.com/"
title: QuarticCat's Blog
paginate: 5
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true
enableInlineShortcodes: true

buildDrafts: false
buildFuture: true # hugo sometimes gets wrong if date format is "yyyy-mm-dd"
buildExpired: false

googleAnalytics: UA-188095502-1

minify:
  disableXML: true
  minifyOutput: true

defaultContentLanguage: en
languages:
  zh:
    languageName: 中文
    weight: 1
    menu:
      main:
        - name: 归档
          url: /archives/
          weight: 10
        - name: 标签
          url: /tags/
          weight: 20
        - name: 搜索
          url: /search/
          weight: 30
        - name: 友链
          url: /blogroll/
          weight: 40
    params:
      DateFormat: 2006-01-02
  en:
    languageName: English
    weight: 2
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 10
        - name: Tags
          url: /tags/
          weight: 20
        - name: Search
          url: /search/
          weight: 30
        - name: Blogroll
          url: /blogroll/
          weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production

  title: QuarticCat's Blog
  description: Write something interesting
  keywords: [Blog, Portfolio, PaperMod]
  author: QuarticCat

  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false

  ShowReadingTime: false # inaccurate for Chinese
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false # inaccurate for Chinese
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  homeInfoParams:
    Title: QuarticCat's Blog
    Content: \> Welcome_

  socialIcons:
    - name: email
      url: "mailto:QuarticCat@pm.me"
    - name: github
      url: "https://github.com/QuarticCat"
    - name: telegram
      url: "https://t.me/QuarticCat"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/14258517"
    - name: twitter
      url: "https://twitter.com/QuarticCat"
    - name: rss
      url: "index.xml"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  assets:
    disableHLJS: true # disable highlight.js

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

markup:
  highlight:
    style: monokai
  goldmark:
    renderer:
      unsafe: true # enable HTML within Markdown
