baseURL: "https://blog.quarticcat.com/"
title: QuarticCat's Blog
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

buildDrafts: false
buildFuture: true # hugo sometimes gets wrong if date format is "yyyy-mm-dd"
buildExpired: false

enableEmoji: true

googleAnalytics: UA-188095502-1

minify:
  disableXML: true
  minifyOutput: true

defaultContentLanguage: en
languages:
  zh:
    languageName: "中文"
    weight: 1
    menu:
      main:
        - name: 归档
          url: /archives/
          weight: 10
        - name: 标签
          url: /tags/
          weight: 20
        - name: 搜索
          url: /search/
          weight: 30
        - name: 友链
          url: /blogroll/
          weight: 40
    params:
      DateFormat: 2006-01-02
  en:
    languageName: "English"
    weight: 2
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 10
        - name: Tags
          url: /tags/
          weight: 20
        - name: Search
          url: /search/
          weight: 30
        - name: Blogroll
          url: /blogroll/
          weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production

  # meta tags
  title: QuarticCat's Blog
  description: Write something interesting
  author: QuarticCat

  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false

  ShowShareButtons: false
  ShowReadingTime: false # inaccurate for Chinese
  ShowBreadCrumbs: false
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

  ShowToc: true
  TocOpen: true

  disableSpecial1stPost: true
  displayFullLangName: true

  homeInfoParams:
    Title: QuarticCat's Blog
    Content: >
      \> Welcome!


      \> Some posts are available in only one language (zh/en).


      \> _

  socialIcons:
    - name: email
      url: "mailto:QuarticCat@pm.me"
    - name: github
      url: "https://github.com/QuarticCat"
    - name: telegram
      url: "https://t.me/QuarticCat"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/14258517/quarticcat"
    - name: twitter
      url: "https://twitter.com/QuarticCat"
    - name: rss
      url: "index.xml"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  assets:
    disableHLJS: true

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]

markup:
  highlight:
    # workaround of https://github.com/adityatelange/hugo-PaperMod/issues/695
    noClasses: true
    style: monokai
  goldmark:
    renderer:
      unsafe: true # enable HTML within Markdown
